### ISSUE TITLE
Running the PluginManager

### ISSUE THREAD

**Issue by usouser** [ChrisMichaelPerezSantiago/123-movies#1]
Hi,

How to run the PluginManager on a website. Can you provide sample code to run on a website. I used the one provided in README and I am unable to use PluginManager as a module.

Regards,
Sam

**Comment by chrismichaelps** [comment]
Hi friend,

Thanks for write!

Unfortunately the API stopped working as the bypass I used for Cloudflare does not bypass correctly, as Cloudflare changed its technique.


This was the way you had to use the module, but first you had to install it from npm


```js
const api = require('123-movies');

(async () => {
  await api.getMovies(1)
    .then(res => console.log(res))
    .catch(err => console.log(err))
})();
```

But as I mentioned earlier, the API stopped working.
My apologies.
